# Render.com deployment configuration
# https://render.com/docs/yaml-spec

services:
  - type: web
    name: lead-scoring-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health/live
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: LOG_LEVEL
        value: info
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: MAX_LEADS_PER_UPLOAD
        value: 1000
      - key: GEMINI_API_KEY
        sync: false  # Set this manually in Render dashboard
    autoDeploy: true
    branch: main
    rootDir: .
    
    # Health check configuration
    healthCheck:
      path: /health/live
      intervalSeconds: 30
      timeoutSeconds: 10
      unhealthyThresholdCount: 3
      healthyThresholdCount: 2
    
    # Resource limits
    disk:
      name: lead-scoring-data
      mountPath: /tmp
      sizeGB: 1